### ISSUE TITLE
Bug in delete routine

### ISSUE THREAD

**Issue by burnsfisher** [zelmon64/zzz-finished-booting-skill#10]
The skill appears to delete the routine, but then throws an uncaught error.  Here is the traceback:

Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/__init__.py", line 338, in _delete_routine
    self._delete_routine_quiet(message)
  File "/opt/mycroft/skills/mycroft_routine_skill.christopherrogers1991/__init__.py", line 346, in _delete_routine_quiet
    self._show_routines()
TypeError: _show_routines() missing 1 required positional argument: 'message'

**Comment by burnsfisher** [comment]
<dope slap>

Sorry this was the WRONG repo that I put this in.  Probably the wrong tab open on my browser!
